from cv2 import *
import numpy
img = imread('../pic/gofy.jpg')
img1 = imread('../pic/lena.jpg')
imshow('origin', img)
imshow('origin1', img1)
img_median1 = blur(img,(5,5))
img_median2 = blur(img,(3,3))
img_median3 = blur(img,(10,10))
img_median = medianBlur(img,7)
img_gaussian = GaussianBlur(img,(5,5),2.0)
img_bilateral = bilateralFilter(img1,30,60,15)
imshow('blur55', img_median1)
imshow('blur33', img_median2)
imshow('blur1010', img_median3)
imshow('medianblur', img_median)
imshow('img_gaussian', img_median)
imshow('img_bilateral', img_bilateral)
waitKey(0)
